language: cpp
sudo: false
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - cmake
    - g++-5

cache:
  - $HOME/boost_1_67_0/boost
  - $HOME/boost_1_67_0/stage/lib

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - wget https://raw.githubusercontent.com/WrinklyNinja/ci-scripts/1.0.0/install_boost.py
  - python install_boost.py --directory ~ --boost-version 1.67.0 system coroutine regex

script:
  - mkdir -p build/
  - cd build
  - cmake ..
  - make
#  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
  - cd ..
