language: cpp
sudo: false
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
#    - libboost1.67-all-dev
    - cmake

script:
  - sudo apt-cache search libboost
  - mkdir -p build/
  - cd build
  - cmake ..
  - make
#  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
  - cd ..
