language: cpp
sudo: false
os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - libboost1.65-all-dev
    - cmake

script:
  - mkdir -p build/
  - cd build
  - cmake ..
  - make
#  - env CTEST_OUTPUT_ON_FAILURE=1 ctest
  - cd ..
